const AUTHORIZATION_REQUEST = 'AUTHORIZATION_REQUEST';
const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';
const AUTHORIZATION_LOGOUT = 'AUTHORIZATION_LOGOUT';
const AUTHORIZATION_LOGIN = 'AUTHORIZATION_LOGIN';

export {AUTHORIZATION_REQUEST, AUTHORIZATION_ERROR, AUTHORIZATION_LOGOUT, AUTHORIZATION_LOGIN};