const CARDS_REQUEST = 'CARDS_REQUEST';
const CARDS_RECEIVE = 'CARDS_RECEIVE';
const CARDS_DATA_CHANGE = 'CARDS_DATA_CHANGE';
const CARDS_ANIMATION = 'CARDS_ANIMATION';

export {CARDS_REQUEST, CARDS_RECEIVE, CARDS_DATA_CHANGE, CARDS_ANIMATION}