const USERS_APP_REQUEST = 'USERS_APP_REQUEST';
const USERS_APP_RECEIVE = 'USERS_APP_RECEIVE';
const USERS_APP_DATA_CHANGE = 'USERS_APP_CHANGE';

export {USERS_APP_REQUEST, USERS_APP_RECEIVE, USERS_APP_DATA_CHANGE}