const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
const USER_INFO_RECEIVE = 'USER_INFO_RECEIVE';
const USER_INFO_DATA_CHANGE = 'USER_INFO_DATA_CHANGE';

export {USER_INFO_REQUEST, USER_INFO_RECEIVE, USER_INFO_DATA_CHANGE}